### ISSUE TITLE
Using SIMD in Swift

### ISSUE THREAD

**Issue by proyb6** [mzaks/FlatBuffersSwift#69]
Opt for SIMD in your code could improve performance.

**Comment by mzaks** [comment]
How can I opt in?

**Comment by proyb6** [comment]
Use _import simd_

http://www.russbishop.net/swift-2-simd

**Comment by mzaks** [comment]
Will have a look, thanks!

**Comment by hassila** [comment]
I think that will make it non-portable for Linux though, that would be bad...

**Comment by mzaks** [comment]
Well the SIMD library let you execute multiple arithmetic operations in the same cpu line. Let say you have a 64 bit CPU and the arithmetic operation can be expressed as 32 bit instruction, than you can schedule two operations at the same time. This is however only possible if the operations are not co-dependent (e.g. vector addition `x1+y1`, `x2+y2` are independent). Most operations we do in flat buffers are co-dependent, because it is basically jumping around in memory and reading data out. So it is not really sufficient IMHO
