### ISSUE TITLE
Option to specify generated class visibility

### ISSUE THREAD

**Issue by mariotaku** [mzaks/FlatBuffersSwift#70]
Thanks for this awesome implementation!

It would be nice if visibility can be changed (to default or internal).

**Comment by mzaks** [comment]
Do you mean for generated classes or for the infrastructure?

**Comment by mariotaku** [comment]
@mzaks Generated classes

**Comment by mzaks** [comment]
Could you please elaborate on that. I just want to understand the use case better.
FlatBuffers support namesapcing which I didn't supported yet because there is no `namespace` concept in Swift. But it would be possible to namespace by nesting classes inside empty enums. At some point I wanted to drop the idea but now I am reevaluating it. specifically if you have multiple `fbs` file wich would like to reuse tables.

**Comment by mariotaku** [comment]
Current implementation only generate public classes, when using in App development, all `extensions` will have to made more public, when developing frameworks, we may want to hide some classes instead of making them public.

**Comment by mzaks** [comment]
You mean if you want to build a Framework which make use of the generated classes and you would not want to expose those classes to the end user (application developer)
OK this is a valid point. I could introduce a custom attribute. It would be specific for FlatBuffersSwift code generator because the main `flatc` code generator doe s not support such feature out of the box afaik.

**Comment by mzaks** [comment]
I created a separate issue in code generation project and I am closing this one.
https://github.com/mzaks/FlatBuffersSwiftCodeGen/issues/7
