### ISSUE TITLE
Can't install through carthage - no ios target

### ISSUE THREAD

**Issue by elimist** [mzaks/FlatBuffersSwift#72]
Hello,

Thank you for making this library!

I'm having some trouble importing it into my ios app -there seems to be no ios target (but there is one for macosx10.11). Im new to Swift/xcode so i'm not sure how to add ios as a target or if this lib is even compatible with it. 

Is there any way to fix this?

**Comment by mzaks** [comment]
I haven't add FlatBuffersSwift to any package manager because the library itself is quite useless :)
The only thing you need is the the code generator. `fbsCG.jar`
The swift file generated by `fbsCG.jar` is self sustained. It already contains the library in the same file.
I made it this way because the generated code and the library are tightly coupled. By shipping only the code generator I reduce the __moving parts__.
There is also a possibility to generate swift file without the library `-lib exclude`. This also a possibility to import the library `-lib import`, but to be honest I don't think it is a good idea for the end user.

**Comment by elimist** [comment]
Thanks for the reply, it makes sense to do it that way from a portability standpoint. The reason I was trying to import it was because I was getting 150+ errors after adding the generated files to my project and most of the errors were "ambiguous type references" and a whole bunch of undefined stuff.

It turns out that happened because I have multiple flatbuffer definition files and I was adding each of the generated swift files to my project which obviously does not work because the library ends up getting included multiple times. 

When I put all the flatbuffer definitions into a single file, compile it and add it my project, everything builds and works great.

Thanks for your help @mzaks and again, thank you for bringing flatbuffers to Swift!

**Comment by elimist** [comment]
Interesting, can you only have one root_type per file? It looks like only the first flatbuffer object is being compiled into Swift when you have  multiple root_types.

**Comment by mzaks** [comment]
Yes just wanted to tel you that if you want to have multiple graphs, you can have multiple `fbs` files and use `-lib exclude` on the second generation call. This way the library will be included only in the first file. There is however the problem if you have same tables in both graphs. `flatc` solves it in the way that it let's user include other `fbs` files. I don't have this feature in `fbsCG` yet. (https://github.com/mzaks/FlatBuffersSwift/issues/48)
